/// Flutter icons Connect
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Connect
///      fonts:
///       - asset: fonts/Connect.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Connect {
  Connect._();

  static const _kFontFam = 'Connect';
  static const String? _kFontPkg = null;

  static const IconData icHome = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icMyPurchase = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icFeed = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icCart = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icProfile = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icCategory = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icLanguage = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icAboutUs = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
